### ISSUE TITLE
[Question] about raspberry pi kernel copy operation

### ISSUE THREAD

**Issue by obi-t4** [tier4/ota-client#194]
@Bodong-Yang 
The comment says:

https://github.com/tier4/ota-client/blob/main/otaclient/app/boot_control/_rpi_boot.py#L396-L398
```python
            # NOTE: if there is multiple kernel, pick the first one we encounted
            # NOTE 2: according to ota-image specification, it should only be one
            #         version of kernel and initrd.img
```

current ota-metadata generator is not picking up the latest kernel, so multiple kernel exists in the under the /boot directory.
Do you think ota-metadata should pickup only one latest kernel image?
(flash-kernel scripts copies latest kernel from multiple kernels under /boot to system-boot partition.

**Comment by Bodong-Yang** [comment]
> Do you think ota-metadata should pickup only one latest kernel image?

@obi-t4 Yes I think so, as multiple kernels actually are not required in our A/B partition environment, each slot uses one kernel is enough.

> (flash-kernel scripts copies latest kernel from multiple kernels under /boot to system-boot partition.
Actually we don't use the kernel copied by flash-kernel(we use `vmlinuz_<slot_id>` instead), we only use it to update the firmware and dtb files. So we don't need to worry about this part. (flash-kernel cannot choose not to copy kernel, so I just leave it as it.)

**Comment by obi-t4** [comment]
OK, I'll add support to pickup latest kernel from /boot directory to the ota-metadata script, thanks!
